[package]
name = "farm-v-13-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.farm-v-13]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.5"
default-features = false
