[package]
name = "locked-token-wrapper-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["MultiversX <contact@multiversx.com>"]

[dev-dependencies]

[dependencies.locked-token-wrapper]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.5"
default-features = false
