[package]
name = "governance-v2-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["MultiversX <contact@multiversx.com>"]

[dev-dependencies]

[dependencies.governance-v2]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.5"
default-features = false
