[package]
name = "simple-lock-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]

[dependencies.simple-lock]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.5"
default-features = false
